const CODE_MAP: Record<string, string> = {
  // CONMEBOL
  'Argentina': 'ar',
  'Brazil': 'br',
  'Uruguay': 'uy',
  'Colombia': 'co',
  'Ecuador': 'ec',
  'Paraguay': 'py',
  'Chile': 'cl',
  'Venezuela': 've',
  'Bolivia': 'bo',
  'Peru': 'pe',

  // CONCACAF
  'United States': 'us',
  'USA': 'us',
  'Mexico': 'mx',
  'Canada': 'ca',
  'Panama': 'pa',
  'Costa Rica': 'cr',
  'Honduras': 'hn',
  'El Salvador': 'sv',
  'Jamaica': 'jm',
  'Trinidad and Tobago': 'tt',
  'Guatemala': 'gt',
  'Cuba': 'cu',
  'Haiti': 'ht',

  // UEFA
  'France': 'fr',
  'England': 'gb-eng',
  'Germany': 'de',
  'Spain': 'es',
  'Portugal': 'pt',
  'Netherlands': 'nl',
  'Italy': 'it',
  'Belgium': 'be',
  'Croatia': 'hr',
  'Switzerland': 'ch',
  'Serbia': 'rs',
  'Poland': 'pl',
  'Turkey': 'tr',
  'Türkiye': 'tr',
  'Austria': 'at',
  'Scotland': 'gb-sct',
  'Wales': 'gb-wls',
  'Hungary': 'hu',
  'Czech Republic': 'cz',
  'Czechia': 'cz',
  'Slovakia': 'sk',
  'Denmark': 'dk',
  'Sweden': 'se',
  'Norway': 'no',
  'Ukraine': 'ua',
  'Romania': 'ro',
  'Greece': 'gr',
  'Albania': 'al',
  'Slovenia': 'si',
  'Iceland': 'is',
  'Northern Ireland': 'gb-nir',
  'Georgia': 'ge',
  'Finland': 'fi',
  'Bulgaria': 'bg',
  'Bosnia and Herzegovina': 'ba',
  'North Macedonia': 'mk',
  'Montenegro': 'me',
  'Ireland': 'ie',
  'Luxembourg': 'lu',

  // CAF
  'Morocco': 'ma',
  'Senegal': 'sn',
  'Egypt': 'eg',
  'Cameroon': 'cm',
  'Nigeria': 'ng',
  'Ghana': 'gh',
  'Ivory Coast': 'ci',
  "Côte d'Ivoire": 'ci',
  'Algeria': 'dz',
  'Tunisia': 'tn',
  'Mali': 'ml',
  'Burkina Faso': 'bf',
  'South Africa': 'za',
  'Zambia': 'zm',
  'Congo': 'cg',
  'DR Congo': 'cd',
  'Tanzania': 'tz',
  'Uganda': 'ug',
  'Cape Verde': 'cv',
  'Guinea': 'gn',
  'Benin': 'bj',
  'Angola': 'ao',
  'Libya': 'ly',
  'Kenya': 'ke',
  'Ethiopia': 'et',
  'Mozambique': 'mz',
  'Gabon': 'ga',
  'Zimbabwe': 'zw',
  'Comoros': 'km',
  'Equatorial Guinea': 'gq',

  // AFC
  'Japan': 'jp',
  'South Korea': 'kr',
  'Korea Republic': 'kr',
  'Australia': 'au',
  'Saudi Arabia': 'sa',
  'Iran': 'ir',
  'Qatar': 'qa',
  'Iraq': 'iq',
  'Bahrain': 'bh',
  'Jordan': 'jo',
  'China': 'cn',
  'China PR': 'cn',
  'United Arab Emirates': 'ae',
  'UAE': 'ae',
  'Uzbekistan': 'uz',
  'Oman': 'om',
  'Kuwait': 'kw',
  'Syria': 'sy',
  'Palestine': 'ps',
  'India': 'in',
  'Thailand': 'th',
  'Vietnam': 'vn',
  'Indonesia': 'id',
  'Malaysia': 'my',
  'Kyrgyzstan': 'kg',
  'Tajikistan': 'tj',

  // OFC
  'New Zealand': 'nz',
  'Solomon Islands': 'sb',
  'Fiji': 'fj',
  'Vanuatu': 'vu',
  'Tahiti': 'pf',
  'Papua New Guinea': 'pg',
};

export function getCountryCode(teamName: string): string | null {
  return CODE_MAP[teamName] ?? null;
}
