const CODE_MAP: Record<string, string> = {
  // ── CONMEBOL (ES + EN) ─────────────────────────────────────────────
  'Argentina': 'ar',
  'Brasil': 'br',   'Brazil': 'br',
  'Uruguay': 'uy',
  'Colombia': 'co',
  'Ecuador': 'ec',
  'Paraguay': 'py',
  'Chile': 'cl',
  'Venezuela': 've',
  'Bolivia': 'bo',
  'Perú': 'pe',     'Peru': 'pe',

  // ── CONCACAF (ES + EN) ────────────────────────────────────────────
  'Estados Unidos': 'us', 'United States': 'us', 'USA': 'us',
  'México': 'mx',         'Mexico': 'mx',
  'Canadá': 'ca',         'Canada': 'ca',
  'Panamá': 'pa',         'Panama': 'pa',
  'Costa Rica': 'cr',
  'Honduras': 'hn',
  'El Salvador': 'sv',
  'Jamaica': 'jm',
  'Trinidad y Tobago': 'tt', 'Trinidad and Tobago': 'tt',
  'Guatemala': 'gt',
  'Cuba': 'cu',
  'Haití': 'ht',          'Haiti': 'ht',
  'Curazao': 'cw',        'Curacao': 'cw', 'Curaçao': 'cw',

  // ── UEFA (ES + EN) ────────────────────────────────────────────────
  'Francia': 'fr',        'France': 'fr',
  'Inglaterra': 'gb-eng', 'England': 'gb-eng',
  'Alemania': 'de',       'Germany': 'de',
  'España': 'es',         'Spain': 'es',
  'Portugal': 'pt',
  'Países Bajos': 'nl',   'Netherlands': 'nl',
  'Italia': 'it',         'Italy': 'it',
  'Bélgica': 'be',        'Belgium': 'be',
  'Croacia': 'hr',        'Croatia': 'hr',
  'Suiza': 'ch',          'Switzerland': 'ch',
  'Serbia': 'rs',
  'Polonia': 'pl',        'Poland': 'pl',
  'Turquía': 'tr',        'Turkey': 'tr', 'Türkiye': 'tr',
  'Austria': 'at',
  'Escocia': 'gb-sct',   'Scotland': 'gb-sct',
  'Gales': 'gb-wls',     'Wales': 'gb-wls',
  'Hungría': 'hu',        'Hungary': 'hu',
  'Chequia': 'cz',        'Czech Republic': 'cz', 'Czechia': 'cz',
  'Eslovaquia': 'sk',     'Slovakia': 'sk',
  'Dinamarca': 'dk',      'Denmark': 'dk',
  'Suecia': 'se',         'Sweden': 'se',
  'Noruega': 'no',        'Norway': 'no',
  'Ucrania': 'ua',        'Ukraine': 'ua',
  'Rumanía': 'ro',        'Romania': 'ro',
  'Grecia': 'gr',         'Greece': 'gr',
  'Albania': 'al',
  'Eslovenia': 'si',      'Slovenia': 'si',
  'Islandia': 'is',       'Iceland': 'is',
  'Irlanda del Norte': 'gb-nir', 'Northern Ireland': 'gb-nir',
  'Georgia': 'ge',
  'Finlandia': 'fi',      'Finland': 'fi',
  'Bulgaria': 'bg',
  'Bosnia y Herzegovina': 'ba', 'Bosnia and Herzegovina': 'ba',
  'Macedonia del Norte': 'mk',  'North Macedonia': 'mk',
  'Montenegro': 'me',
  'Irlanda': 'ie',        'Ireland': 'ie',
  'Luxemburgo': 'lu',     'Luxembourg': 'lu',

  // ── CAF (ES + EN) ────────────────────────────────────────────────
  'Marruecos': 'ma',      'Morocco': 'ma',
  'Senegal': 'sn',
  'Egipto': 'eg',         'Egypt': 'eg',
  'Camerún': 'cm',        'Cameroon': 'cm',
  'Nigeria': 'ng',
  'Ghana': 'gh',
  'Costa de Marfil': 'ci', 'Ivory Coast': 'ci', "Côte d'Ivoire": 'ci',
  'Argelia': 'dz',        'Algeria': 'dz',
  'Túnez': 'tn',          'Tunisia': 'tn',
  'Malí': 'ml',           'Mali': 'ml',
  'Burkina Faso': 'bf',
  'Sudáfrica': 'za',      'South Africa': 'za',
  'Zambia': 'zm',
  'Congo': 'cg',
  'Rep. Dem. del Congo': 'cd', 'DR Congo': 'cd',
  'Tanzania': 'tz',
  'Uganda': 'ug',
  'Cabo Verde': 'cv',     'Cape Verde': 'cv',
  'Guinea': 'gn',
  'Benín': 'bj',          'Benin': 'bj',
  'Angola': 'ao',
  'Libia': 'ly',          'Libya': 'ly',
  'Kenia': 'ke',          'Kenya': 'ke',
  'Etiopía': 'et',        'Ethiopia': 'et',
  'Mozambique': 'mz',
  'Gabón': 'ga',          'Gabon': 'ga',
  'Zimbabue': 'zw',       'Zimbabwe': 'zw',
  'Comoras': 'km',        'Comoros': 'km',
  'Guinea Ecuatorial': 'gq', 'Equatorial Guinea': 'gq',

  // ── AFC (ES + EN) ────────────────────────────────────────────────
  'Japón': 'jp',          'Japan': 'jp',
  'Corea del Sur': 'kr',  'South Korea': 'kr', 'Korea Republic': 'kr',
  'Australia': 'au',
  'Arabia Saudita': 'sa', 'Saudi Arabia': 'sa',
  'Irán': 'ir',           'Iran': 'ir',
  'Catar': 'qa',          'Qatar': 'qa',
  'Irak': 'iq',           'Iraq': 'iq',
  'Baréin': 'bh',         'Bahrain': 'bh',
  'Jordania': 'jo',       'Jordan': 'jo',
  'China': 'cn',          'China PR': 'cn',
  'Emiratos Árabes Unidos': 'ae', 'United Arab Emirates': 'ae', 'UAE': 'ae',
  'Uzbekistán': 'uz',     'Uzbekistan': 'uz',
  'Omán': 'om',           'Oman': 'om',
  'Kuwait': 'kw',
  'Siria': 'sy',          'Syria': 'sy',
  'Palestina': 'ps',      'Palestine': 'ps',
  'India': 'in',
  'Tailandia': 'th',      'Thailand': 'th',
  'Vietnam': 'vn',
  'Indonesia': 'id',
  'Malasia': 'my',        'Malaysia': 'my',
  'Kirguistán': 'kg',     'Kyrgyzstan': 'kg',
  'Tayikistán': 'tj',     'Tajikistan': 'tj',

  // ── OFC (ES + EN) ────────────────────────────────────────────────
  'Nueva Zelanda': 'nz',  'New Zealand': 'nz',
  'Islas Salomón': 'sb',  'Solomon Islands': 'sb',
  'Fiyi': 'fj',           'Fiji': 'fj',
  'Vanuatu': 'vu',
  'Tahití': 'pf',         'Tahiti': 'pf',
  'Papúa Nueva Guinea': 'pg', 'Papua New Guinea': 'pg',
};

export function getCountryCode(teamName: string): string | null {
  return CODE_MAP[teamName] ?? null;
}
